# Setup
name:         qpointwang
tagline:      qpointwang's home
baseurl:      ""
locale:       "en"

permalink: :year/:month/:day/:title/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
